displayName=Ring of Recoil Helper
author=Darkwell
description=A plugin which helps with the regular usage of jewelry with recoiling effects.
support=https://github.com/mdarkwell/ring-of-recoil-helper/blob/master/README.md
tags=recoiling,effect,jewelry,ring,of,recoil,suffering,charge,charges,(r),(i),(ri)
plugins=com.darkwell.rorh.RingOfRecoilPlugin
version=1.0.0
build=standard
